INSERT INTO HOTEL (NAME, DESCRIPTION, PRICE) VALUES 
('PARADAISE', 'ALUVA', 1000),
('HOTEL GREEN PARK', 'KALOOR', 2000),
('HOTEL HOLIDAY INN', 'KAKKANAD', 3000),
('HOTEL MARRIOT', 'EDAPPALLY', 4000),
('HOTEL RADISSON', 'VYTTILA', 5000);